name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Build AAB
      run: ./gradlew bundleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-release.aab
        path: app/build/outputs/bundle/release/app-re
        lease.aab
